//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.sbml.sbml.level2.version4;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sbml.sbml.level2.version4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sbml.sbml.level2.version4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OriginalModel }
     * 
     */
    public OriginalModel createOriginalModel() {
        return new OriginalModel();
    }

    /**
     * Create an instance of {@link Sbml }
     * 
     */
    public Sbml createSbml() {
        return new Sbml();
    }

    /**
     * Create an instance of {@link org.sbml.sbml.level2.version4.SBase.Notes }
     * 
     */
    public org.sbml.sbml.level2.version4.SBase.Notes createSBaseNotes() {
        return new org.sbml.sbml.level2.version4.SBase.Notes();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link SpeciesReference }
     * 
     */
    public SpeciesReference createSpeciesReference() {
        return new SpeciesReference();
    }

    /**
     * Create an instance of {@link ListOfSpeciesReferences }
     * 
     */
    public ListOfSpeciesReferences createListOfSpeciesReferences() {
        return new ListOfSpeciesReferences();
    }

    /**
     * Create an instance of {@link Compartment }
     * 
     */
    public Compartment createCompartment() {
        return new Compartment();
    }

    /**
     * Create an instance of {@link ModifierSpeciesReference }
     * 
     */
    public ModifierSpeciesReference createModifierSpeciesReference() {
        return new ModifierSpeciesReference();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link FunctionDefinition }
     * 
     */
    public FunctionDefinition createFunctionDefinition() {
        return new FunctionDefinition();
    }

    /**
     * Create an instance of {@link EventAssignment }
     * 
     */
    public EventAssignment createEventAssignment() {
        return new EventAssignment();
    }

    /**
     * Create an instance of {@link ListOfModifierSpeciesReferences }
     * 
     */
    public ListOfModifierSpeciesReferences createListOfModifierSpeciesReferences() {
        return new ListOfModifierSpeciesReferences();
    }

    /**
     * Create an instance of {@link ListOfUnits }
     * 
     */
    public ListOfUnits createListOfUnits() {
        return new ListOfUnits();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Species }
     * 
     */
    public Species createSpecies() {
        return new Species();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link KineticLaw }
     * 
     */
    public KineticLaw createKineticLaw() {
        return new KineticLaw();
    }

    /**
     * Create an instance of {@link ListOfEventAssignments }
     * 
     */
    public ListOfEventAssignments createListOfEventAssignments() {
        return new ListOfEventAssignments();
    }

    /**
     * Create an instance of {@link AlgebraicRule }
     * 
     */
    public AlgebraicRule createAlgebraicRule() {
        return new AlgebraicRule();
    }

    /**
     * Create an instance of {@link org.sbml.sbml.level2.version4.ListOfParameters }
     * 
     */
    public org.sbml.sbml.level2.version4.ListOfParameters createListOfParameters() {
        return new org.sbml.sbml.level2.version4.ListOfParameters();
    }

    /**
     * Create an instance of {@link StoichiometryMath }
     * 
     */
    public StoichiometryMath createStoichiometryMath() {
        return new StoichiometryMath();
    }

    /**
     * Create an instance of {@link UnitDefinition }
     * 
     */
    public UnitDefinition createUnitDefinition() {
        return new UnitDefinition();
    }

    /**
     * Create an instance of {@link Reaction }
     * 
     */
    public Reaction createReaction() {
        return new Reaction();
    }

    /**
     * Create an instance of {@link MathField }
     * 
     */
    public MathField createMathField() {
        return new MathField();
    }

    /**
     * Create an instance of {@link AssignmentRule }
     * 
     */
    public AssignmentRule createAssignmentRule() {
        return new AssignmentRule();
    }

    /**
     * Create an instance of {@link RateRule }
     * 
     */
    public RateRule createRateRule() {
        return new RateRule();
    }

    /**
     * Create an instance of {@link OriginalReaction }
     * 
     */
    public OriginalReaction createOriginalReaction() {
        return new OriginalReaction();
    }

    /**
     * Create an instance of {@link OriginalSpecies }
     * 
     */
    public OriginalSpecies createOriginalSpecies() {
        return new OriginalSpecies();
    }

    /**
     * Create an instance of {@link OriginalModifierSpeciesReference }
     * 
     */
    public OriginalModifierSpeciesReference createOriginalModifierSpeciesReference() {
        return new OriginalModifierSpeciesReference();
    }

    /**
     * Create an instance of {@link OriginalCompartment }
     * 
     */
    public OriginalCompartment createOriginalCompartment() {
        return new OriginalCompartment();
    }

    /**
     * Create an instance of {@link OriginalSpeciesReference }
     * 
     */
    public OriginalSpeciesReference createOriginalSpeciesReference() {
        return new OriginalSpeciesReference();
    }

    /**
     * Create an instance of {@link OriginalModel.ListOfFunctionDefinitions }
     * 
     */
    public OriginalModel.ListOfFunctionDefinitions createOriginalModelListOfFunctionDefinitions() {
        return new OriginalModel.ListOfFunctionDefinitions();
    }

    /**
     * Create an instance of {@link OriginalModel.ListOfUnitDefinitions }
     * 
     */
    public OriginalModel.ListOfUnitDefinitions createOriginalModelListOfUnitDefinitions() {
        return new OriginalModel.ListOfUnitDefinitions();
    }

    /**
     * Create an instance of {@link OriginalModel.ListOfCompartments }
     * 
     */
    public OriginalModel.ListOfCompartments createOriginalModelListOfCompartments() {
        return new OriginalModel.ListOfCompartments();
    }

    /**
     * Create an instance of {@link OriginalModel.ListOfSpecies }
     * 
     */
    public OriginalModel.ListOfSpecies createOriginalModelListOfSpecies() {
        return new OriginalModel.ListOfSpecies();
    }

    /**
     * Create an instance of {@link OriginalModel.ListOfParameters }
     * 
     */
    public OriginalModel.ListOfParameters createOriginalModelListOfParameters() {
        return new OriginalModel.ListOfParameters();
    }

    /**
     * Create an instance of {@link OriginalModel.ListOfRules }
     * 
     */
    public OriginalModel.ListOfRules createOriginalModelListOfRules() {
        return new OriginalModel.ListOfRules();
    }

    /**
     * Create an instance of {@link OriginalModel.ListOfReactions }
     * 
     */
    public OriginalModel.ListOfReactions createOriginalModelListOfReactions() {
        return new OriginalModel.ListOfReactions();
    }

    /**
     * Create an instance of {@link OriginalModel.ListOfEvents }
     * 
     */
    public OriginalModel.ListOfEvents createOriginalModelListOfEvents() {
        return new OriginalModel.ListOfEvents();
    }

}
