//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.sbml.sbml.level2.version4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeciesReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeciesReference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sbml.org/sbml/level2/version4}SimpleSpeciesReference">
 *       &lt;sequence>
 *         &lt;element name="stoichiometryMath" type="{http://www.sbml.org/sbml/level2/version4}StoichiometryMath" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="stoichiometry" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stoichiometryMath"
})
@XmlSeeAlso({
    SpeciesReference.class
})
public class OriginalSpeciesReference
    extends SimpleSpeciesReference
{

    protected StoichiometryMath stoichiometryMath;
    @XmlAttribute(name = "stoichiometry")
    protected Double stoichiometry;

    /**
     * Gets the value of the stoichiometryMath property.
     * 
     * @return
     *     possible object is
     *     {@link StoichiometryMath }
     *     
     */
    public StoichiometryMath getStoichiometryMath() {
        return stoichiometryMath;
    }

    /**
     * Sets the value of the stoichiometryMath property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoichiometryMath }
     *     
     */
    public void setStoichiometryMath(StoichiometryMath value) {
        this.stoichiometryMath = value;
    }

    /**
     * Gets the value of the stoichiometry property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getStoichiometry() {
        if (stoichiometry == null) {
            return  1.0D;
        } else {
            return stoichiometry;
        }
    }

    /**
     * Sets the value of the stoichiometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStoichiometry(Double value) {
        this.stoichiometry = value;
    }

}
