/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml.sbml.level2.version4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for SpeciesReference complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SpeciesReference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sbml.org/sbml/level2/version4}SimpleSpeciesReference">
 *       &lt;sequence>
 *         &lt;element name="stoichiometryMath" type="{http://www.sbml.org/sbml/level2/version4}StoichiometryMath" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="stoichiometry" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"stoichiometryMath"})
@XmlSeeAlso({SpeciesReference.class})
public class OriginalSpeciesReference extends SimpleSpeciesReference {

  /** The stoichiometry math. */
  protected StoichiometryMath stoichiometryMath;
  /** The stoichiometry. */
  @XmlAttribute(name = "stoichiometry")
  protected Double            stoichiometry;


  /**
   * Gets the value of the stoichiometryMath property.
   * 
   * @return
   *         possible object is {@link StoichiometryMath }
   */
  public StoichiometryMath getStoichiometryMath() {
    return stoichiometryMath;
  }


  /**
   * Sets the value of the stoichiometryMath property.
   * 
   * @param value
   *        allowed object is {@link StoichiometryMath }
   */
  public void setStoichiometryMath(StoichiometryMath value) {
    this.stoichiometryMath = value;
  }


  /**
   * Gets the value of the stoichiometry property.
   * 
   * @return
   *         possible object is {@link Double }
   */
  public double getStoichiometry() {
    if (stoichiometry == null) {
      return 1.0D;
    } else {
      return stoichiometry;
    }
  }


  /**
   * Sets the value of the stoichiometry property.
   * 
   * @param value
   *        allowed object is {@link Double }
   */
  public void setStoichiometry(Double value) {
    this.stoichiometry = value;
  }
}
