//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sbml.org/sbml/level2/version4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sbml.sbml.level2.version4;
