/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml.sbml.level2.version4;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for Unit complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Unit">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sbml.org/sbml/level2/version4}SBase">
 *       &lt;attribute name="kind" use="required" type="{http://www.sbml.org/sbml/level2/version4}UnitKind" />
 *       &lt;attribute name="exponent" type="{http://www.w3.org/2001/XMLSchema}integer" default="1" />
 *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}integer" default="0" />
 *       &lt;attribute name="multiplier" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Unit")
public class Unit extends SBase {

  /** The kind. */
  @XmlAttribute(name = "kind", required = true)
  protected UnitKind   kind;
  /** The exponent. */
  @XmlAttribute(name = "exponent")
  protected BigInteger exponent;
  /** The scale. */
  @XmlAttribute(name = "scale")
  protected BigInteger scale;
  /** The multiplier. */
  @XmlAttribute(name = "multiplier")
  protected Double     multiplier;
  /** The offset. */
  @XmlAttribute(name = "offset")
  protected Double     offset;


  /**
   * Gets the value of the kind property.
   * 
   * @return
   *         possible object is {@link UnitKind }
   */
  public UnitKind getKind() {
    return kind;
  }


  /**
   * Sets the value of the kind property.
   * 
   * @param value
   *        allowed object is {@link UnitKind }
   */
  public void setKind(UnitKind value) {
    this.kind = value;
  }


  /**
   * Gets the value of the exponent property.
   * 
   * @return
   *         possible object is {@link BigInteger }
   */
  public BigInteger getExponent() {
    if (exponent == null) {
      return new BigInteger("1");
    } else {
      return exponent;
    }
  }


  /**
   * Sets the value of the exponent property.
   * 
   * @param value
   *        allowed object is {@link BigInteger }
   */
  public void setExponent(BigInteger value) {
    this.exponent = value;
  }


  /**
   * Gets the value of the scale property.
   * 
   * @return
   *         possible object is {@link BigInteger }
   */
  public BigInteger getScale() {
    if (scale == null) {
      return new BigInteger("0");
    } else {
      return scale;
    }
  }


  /**
   * Sets the value of the scale property.
   * 
   * @param value
   *        allowed object is {@link BigInteger }
   */
  public void setScale(BigInteger value) {
    this.scale = value;
  }


  /**
   * Gets the value of the multiplier property.
   * 
   * @return
   *         possible object is {@link Double }
   */
  public double getMultiplier() {
    if (multiplier == null) {
      return 1.0D;
    } else {
      return multiplier;
    }
  }


  /**
   * Sets the value of the multiplier property.
   * 
   * @param value
   *        allowed object is {@link Double }
   */
  public void setMultiplier(Double value) {
    this.multiplier = value;
  }


  /**
   * Gets the value of the offset property.
   * 
   * @return
   *         possible object is {@link Double }
   */
  public double getOffset() {
    if (offset == null) {
      return 0.0D;
    } else {
      return offset;
    }
  }


  /**
   * Sets the value of the offset property.
   * 
   * @param value
   *        allowed object is {@link Double }
   */
  public void setOffset(Double value) {
    this.offset = value;
  }
}
