package fr.curie.cd2sbgnml.xmlcdwrappers;

/**
 * Possible values for the 'type' attribute of the 'modification' xml element.
 */
public enum ModificationLinkType {
    CATALYSIS, UNKNOWN_CATALYSIS,
    INHIBITION, UNKNOWN_INHIBITION,
    TRANSPORT,
    HETERODIMER_ASSOCIATION, DISSOCIATION,
    TRANSCRIPTIONAL_ACTIVATION, TRANSCRIPTIONAL_INHIBITION,
    TRANSLATIONAL_ACTIVATION, TRANSLATIONAL_INHIBITION,
    PHYSICAL_STIMULATION, MODULATION, TRIGGER,
    REDUCED_TRIGGER, NEGATIVE_INFLUENCE, POSITIVE_INFLUENCE, UNKNOWN_POSITIVE_INFLUENCE,
    BOOLEAN_LOGIC_GATE_OR,
    BOOLEAN_LOGIC_GATE_AND,
    BOOLEAN_LOGIC_GATE_NOT,
    BOOLEAN_LOGIC_GATE_UNKNOWN
}
