package fr.curie.cd2sbgnml.xmlcdwrappers;

/**
 * Possible values for the reactionType element of CellDesigner reactions.
 */
public enum ReactionType {

    STATE_TRANSITION, HETERODIMER_ASSOCIATION, DISSOCIATION,

    KNOWN_TRANSITION_OMITTED, UNKNOWN_TRANSITION,
    CATALYSIS, UNKNOWN_CATALYSIS,
    INHIBITION, UNKNOWN_INHIBITION,
    TRANSPORT, TRUNCATION, TRANSCRIPTION, TRANSLATION,
    TRANSCRIPTIONAL_ACTIVATION, TRANSCRIPTIONAL_INHIBITION,
    TRANSLATIONAL_ACTIVATION, TRANSLATIONAL_INHIBITION,
    MODULATION, REDUCED_MODULATION, UNKNOWN_REDUCED_MODULATION,
    TRIGGER, REDUCED_TRIGGER, UNKNOWN_REDUCED_TRIGGER,
    PHYSICAL_STIMULATION, REDUCED_PHYSICAL_STIMULATION, UNKNOWN_REDUCED_PHYSICAL_STIMULATION,
    NEGATIVE_INFLUENCE, UNKNOWN_NEGATIVE_INFLUENCE,
    POSITIVE_INFLUENCE, UNKNOWN_POSITIVE_INFLUENCE,

    /**
     * When the reaction involves only a logic gate, pointing directly at en entity, with no process involved.
     */
    BOOLEAN_LOGIC_GATE
}
