/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml._2001.ns.celldesigner;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * Type and targets of an effect.
 * <p>
 * Java class for effectInBlockDiagram complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="effectInBlockDiagram">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="effectTargetInBlockDiagram" type="{http://www.sbml.org/2001/ns/celldesigner}effectTargetInBlockDiagram" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="CATALYSIS"/>
 *             &lt;enumeration value="INHIBITION"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "effectInBlockDiagram", propOrder = {"effectTargetInBlockDiagram"})
public class EffectInBlockDiagram {

  /** The effect target in block diagram. */
  @XmlElement(required = true)
  protected List<EffectTargetInBlockDiagram> effectTargetInBlockDiagram;
  /** The type. */
  @XmlAttribute(name = "type", required = true)
  protected String                           type;


  /**
   * Gets the value of the effectTargetInBlockDiagram property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the effectTargetInBlockDiagram property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getEffectTargetInBlockDiagram().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link EffectTargetInBlockDiagram }
   *
   * @return the effect target in block diagram
   */
  public List<EffectTargetInBlockDiagram> getEffectTargetInBlockDiagram() {
    if (effectTargetInBlockDiagram == null) {
      effectTargetInBlockDiagram = new ArrayList<EffectTargetInBlockDiagram>();
    }
    return this.effectTargetInBlockDiagram;
  }


  /**
   * Gets the value of the type property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getType() {
    return type;
  }


  /**
   * Sets the value of the type property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }
}
