/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml._2001.ns.celldesigner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * For gene.
 * <p>
 * Java class for gene complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="gene">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="notes" type="{http://www.sbml.org/2001/ns/celldesigner}notes" minOccurs="0"/>
 *         &lt;element name="listOfRegions" type="{http://www.sbml.org/2001/ns/celldesigner}listOfRegions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sbml.org/2001/ns/celldesigner}SId">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="GENE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gene", propOrder = {"notes", "listOfRegions"})
public class Gene {

  /** The notes. */
  protected Notes         notes;
  /** The list of regions. */
  protected ListOfRegions listOfRegions;
  /** The id. */
  @XmlAttribute(name = "id", required = true)
  protected String        id;
  /** The name. */
  @XmlAttribute(name = "name", required = true)
  protected String        name;
  /** The type. */
  @XmlAttribute(name = "type", required = true)
  protected String        type;


  /**
   * Gets the value of the notes property.
   * 
   * @return
   *         possible object is {@link Notes }
   */
  public Notes getNotes() {
    return notes;
  }


  /**
   * Sets the value of the notes property.
   * 
   * @param value
   *        allowed object is {@link Notes }
   */
  public void setNotes(Notes value) {
    this.notes = value;
  }


  /**
   * Gets the value of the listOfRegions property.
   * 
   * @return
   *         possible object is {@link ListOfRegions }
   */
  public ListOfRegions getListOfRegions() {
    return listOfRegions;
  }


  /**
   * Sets the value of the listOfRegions property.
   * 
   * @param value
   *        allowed object is {@link ListOfRegions }
   */
  public void setListOfRegions(ListOfRegions value) {
    this.listOfRegions = value;
  }


  /**
   * Gets the value of the id property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getId() {
    return id;
  }


  /**
   * Sets the value of the id property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }


  /**
   * Gets the value of the name property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getName() {
    return name;
  }


  /**
   * Sets the value of the name property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }


  /**
   * Gets the value of the type property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getType() {
    return type;
  }


  /**
   * Sets the value of the type property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }
}
