/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml._2001.ns.celldesigner;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for layerLineBounds complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="layerLineBounds">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sx" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="sy" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="ex" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="ey" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "layerLineBounds")
public class LayerLineBounds {

  /** The sx. */
  @XmlAttribute(name = "sx")
  protected BigDecimal sx;
  /** The sy. */
  @XmlAttribute(name = "sy")
  protected BigDecimal sy;
  /** The ex. */
  @XmlAttribute(name = "ex")
  protected BigDecimal ex;
  /** The ey. */
  @XmlAttribute(name = "ey")
  protected BigDecimal ey;


  /**
   * Gets the value of the sx property.
   * 
   * @return
   *         possible object is {@link BigDecimal }
   */
  public BigDecimal getSx() {
    return sx;
  }


  /**
   * Sets the value of the sx property.
   * 
   * @param value
   *        allowed object is {@link BigDecimal }
   */
  public void setSx(BigDecimal value) {
    this.sx = value;
  }


  /**
   * Gets the value of the sy property.
   * 
   * @return
   *         possible object is {@link BigDecimal }
   */
  public BigDecimal getSy() {
    return sy;
  }


  /**
   * Sets the value of the sy property.
   * 
   * @param value
   *        allowed object is {@link BigDecimal }
   */
  public void setSy(BigDecimal value) {
    this.sy = value;
  }


  /**
   * Gets the value of the ex property.
   * 
   * @return
   *         possible object is {@link BigDecimal }
   */
  public BigDecimal getEx() {
    return ex;
  }


  /**
   * Sets the value of the ex property.
   * 
   * @param value
   *        allowed object is {@link BigDecimal }
   */
  public void setEx(BigDecimal value) {
    this.ex = value;
  }


  /**
   * Gets the value of the ey property.
   * 
   * @return
   *         possible object is {@link BigDecimal }
   */
  public BigDecimal getEy() {
    return ey;
  }


  /**
   * Sets the value of the ey property.
   * 
   * @param value
   *        allowed object is {@link BigDecimal }
   */
  public void setEy(BigDecimal value) {
    this.ey = value;
  }
}
