/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml._2001.ns.celldesigner;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * Line color, width and curve style.
 * <p>
 * Java class for lineType2 complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lineType2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="color" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9a-fA-F]{8}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="width" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Curve"/>
 *             &lt;enumeration value="Straight"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lineType2")
public class LineType2 {

  /** The color. */
  @XmlAttribute(name = "color", required = true)
  protected String     color;
  /** The width. */
  @XmlAttribute(name = "width", required = true)
  protected BigDecimal width;
  /** The type. */
  @XmlAttribute(name = "type", required = true)
  protected String     type;


  /**
   * Gets the value of the color property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getColor() {
    return color;
  }


  /**
   * Sets the value of the color property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setColor(String value) {
    this.color = value;
  }


  /**
   * Gets the value of the width property.
   * 
   * @return
   *         possible object is {@link BigDecimal }
   */
  public BigDecimal getWidth() {
    return width;
  }


  /**
   * Sets the value of the width property.
   * 
   * @param value
   *        allowed object is {@link BigDecimal }
   */
  public void setWidth(BigDecimal value) {
    this.width = value;
  }


  /**
   * Gets the value of the type property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getType() {
    return type;
  }


  /**
   * Sets the value of the type property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }
}
