/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml._2001.ns.celldesigner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * Line direction designator.
 * <p>
 * Java class for lineDirection complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lineDirection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="index" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="value" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="horizontal"/>
 *             &lt;enumeration value="vertical"/>
 *             &lt;enumeration value="unknown"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="arm">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lineDirection")
public class LineDirection {

  /** The index. */
  @XmlAttribute(name = "index", required = true)
  protected short  index;
  /** The value. */
  @XmlAttribute(name = "value", required = true)
  protected String value;
  /** The arm. */
  @XmlAttribute(name = "arm")
  protected Short  arm;


  /**
   * Gets the value of the index property.
   *
   * @return the index
   */
  public short getIndex() {
    return index;
  }


  /**
   * Sets the value of the index property.
   *
   * @param value
   *        the new index
   */
  public void setIndex(short value) {
    this.index = value;
  }


  /**
   * Gets the value of the value property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getValue() {
    return value;
  }


  /**
   * Sets the value of the value property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setValue(String value) {
    this.value = value;
  }


  /**
   * Gets the value of the arm property.
   * 
   * @return
   *         possible object is {@link Short }
   */
  public Short getArm() {
    return arm;
  }


  /**
   * Sets the value of the arm property.
   * 
   * @param value
   *        allowed object is {@link Short }
   */
  public void setArm(Short value) {
    this.arm = value;
  }
}
