/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml._2001.ns.celldesigner;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * Line modification.
 * <p>
 * Java class for modification complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="modification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connectScheme" type="{http://www.sbml.org/2001/ns/celldesigner}connectScheme" minOccurs="0"/>
 *         &lt;element name="linkTarget" type="{http://www.sbml.org/2001/ns/celldesigner}linkTarget" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="line" type="{http://www.sbml.org/2001/ns/celldesigner}line" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="aliases" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sbml.org/2001/ns/celldesigner}SIdSet">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="modifiers" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sbml.org/2001/ns/celldesigner}SIdSet">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="CATALYSIS"/>
 *             &lt;enumeration value="UNKNOWN_CATALYSIS"/>
 *             &lt;enumeration value="INHIBITION"/>
 *             &lt;enumeration value="UNKNOWN_INHIBITION"/>
 *             &lt;enumeration value="HETERODIMER_ASSOCIATION"/>
 *             &lt;enumeration value="TRANSCRIPTIONAL_ACTIVATION"/>
 *             &lt;enumeration value="TRANSCRIPTIONAL_INHIBITION"/>
 *             &lt;enumeration value="TRANSLATIONAL_ACTIVATION"/>
 *             &lt;enumeration value="TRANSLATIONAL_INHIBITION"/>
 *             &lt;enumeration value="PHYSICAL_STIMULATION"/>
 *             &lt;enumeration value="MODULATION"/>
 *             &lt;enumeration value="TRIGGER"/>
 *             &lt;enumeration value="BOOLEAN_LOGIC_GATE_AND"/>
 *             &lt;enumeration value="BOOLEAN_LOGIC_GATE_OR"/>
 *             &lt;enumeration value="BOOLEAN_LOGIC_GATE_NOT"/>
 *             &lt;enumeration value="BOOLEAN_LOGIC_GATE_UNKNOWN"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="targetLineIndex" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="-?[0-9]+,[0-9]+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="editPoints">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sbml.org/2001/ns/celldesigner}point2DList">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="num0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="num1">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="num2">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="modification">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="CATALYSIS"/>
 *             &lt;enumeration value="UNKNOWN_CATALYSIS"/>
 *             &lt;enumeration value="INHIBITION"/>
 *             &lt;enumeration value="UNKNOWN_INHIBITION"/>
 *             &lt;enumeration value="HETERODIMER_ASSOCIATION"/>
 *             &lt;enumeration value="TRANSCRIPTIONAL_ACTIVATION"/>
 *             &lt;enumeration value="TRANSCRIPTIONAL_INHIBITION"/>
 *             &lt;enumeration value="TRANSLATIONAL_ACTIVATION"/>
 *             &lt;enumeration value="TRANSLATIONAL_INHIBITION"/>
 *             &lt;enumeration value="PHYSICAL_STIMULATION"/>
 *             &lt;enumeration value="MODULATION"/>
 *             &lt;enumeration value="TRIGGER"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="offsetX">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="offsetY">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modification", propOrder = {"connectScheme", "linkTarget",
  "line"})
public class Modification {

  /** The connect scheme. */
  protected ConnectScheme    connectScheme;
  /** The link target. */
  protected List<LinkTarget> linkTarget;
  /** The line. */
  protected Line             line;
  /** The aliases. */
  @XmlAttribute(name = "aliases", required = true)
  protected String           aliases;
  /** The modifiers. */
  @XmlAttribute(name = "modifiers", required = true)
  protected String           modifiers;
  /** The type. */
  @XmlAttribute(name = "type", required = true)
  protected String           type;
  /** The target line index. */
  @XmlAttribute(name = "targetLineIndex", required = true)
  protected String           targetLineIndex;
  /** The edit points. */
  @XmlAttribute(name = "editPoints")
  protected List<String>     editPoints;
  /** The num 0. */
  @XmlAttribute(name = "num0")
  protected BigInteger       num0;
  /** The num 1. */
  @XmlAttribute(name = "num1")
  protected BigInteger       num1;
  /** The num 2. */
  @XmlAttribute(name = "num2")
  protected BigInteger       num2;
  /** The modification. */
  @XmlAttribute(name = "modification")
  protected String           modification;
  /** The offset X. */
  @XmlAttribute(name = "offsetX")
  protected BigDecimal       offsetX;
  /** The offset Y. */
  @XmlAttribute(name = "offsetY")
  protected BigDecimal       offsetY;


  /**
   * Gets the value of the connectScheme property.
   * 
   * @return
   *         possible object is {@link ConnectScheme }
   */
  public ConnectScheme getConnectScheme() {
    return connectScheme;
  }


  /**
   * Sets the value of the connectScheme property.
   * 
   * @param value
   *        allowed object is {@link ConnectScheme }
   */
  public void setConnectScheme(ConnectScheme value) {
    this.connectScheme = value;
  }


  /**
   * Gets the value of the linkTarget property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the linkTarget property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getLinkTarget().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list {@link LinkTarget }
   *
   * @return the link target
   */
  public List<LinkTarget> getLinkTarget() {
    if (linkTarget == null) {
      linkTarget = new ArrayList<LinkTarget>();
    }
    return this.linkTarget;
  }


  /**
   * Gets the value of the line property.
   * 
   * @return
   *         possible object is {@link Line }
   */
  public Line getLine() {
    return line;
  }


  /**
   * Sets the value of the line property.
   * 
   * @param value
   *        allowed object is {@link Line }
   */
  public void setLine(Line value) {
    this.line = value;
  }


  /**
   * Gets the value of the aliases property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getAliases() {
    return aliases;
  }


  /**
   * Sets the value of the aliases property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setAliases(String value) {
    this.aliases = value;
  }


  /**
   * Gets the value of the modifiers property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getModifiers() {
    return modifiers;
  }


  /**
   * Sets the value of the modifiers property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setModifiers(String value) {
    this.modifiers = value;
  }


  /**
   * Gets the value of the type property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getType() {
    return type;
  }


  /**
   * Sets the value of the type property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }


  /**
   * Gets the value of the targetLineIndex property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getTargetLineIndex() {
    return targetLineIndex;
  }


  /**
   * Sets the value of the targetLineIndex property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setTargetLineIndex(String value) {
    this.targetLineIndex = value;
  }


  /**
   * Gets the value of the editPoints property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the editPoints property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getEditPoints().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list {@link String }
   *
   * @return the edits the points
   */
  public List<String> getEditPoints() {
    if (editPoints == null) {
      editPoints = new ArrayList<String>();
    }
    return this.editPoints;
  }


  /**
   * Gets the value of the num0 property.
   * 
   * @return
   *         possible object is {@link BigInteger }
   */
  public BigInteger getNum0() {
    return num0;
  }


  /**
   * Sets the value of the num0 property.
   * 
   * @param value
   *        allowed object is {@link BigInteger }
   */
  public void setNum0(BigInteger value) {
    this.num0 = value;
  }


  /**
   * Gets the value of the num1 property.
   * 
   * @return
   *         possible object is {@link BigInteger }
   */
  public BigInteger getNum1() {
    return num1;
  }


  /**
   * Sets the value of the num1 property.
   * 
   * @param value
   *        allowed object is {@link BigInteger }
   */
  public void setNum1(BigInteger value) {
    this.num1 = value;
  }


  /**
   * Gets the value of the num2 property.
   * 
   * @return
   *         possible object is {@link BigInteger }
   */
  public BigInteger getNum2() {
    return num2;
  }


  /**
   * Sets the value of the num2 property.
   * 
   * @param value
   *        allowed object is {@link BigInteger }
   */
  public void setNum2(BigInteger value) {
    this.num2 = value;
  }


  /**
   * Gets the value of the modification property.
   * 
   * @return
   *         possible object is {@link String }
   */
  public String getModification() {
    return modification;
  }


  /**
   * Sets the value of the modification property.
   * 
   * @param value
   *        allowed object is {@link String }
   */
  public void setModification(String value) {
    this.modification = value;
  }


  /**
   * Gets the value of the offsetX property.
   * 
   * @return
   *         possible object is {@link BigDecimal }
   */
  public BigDecimal getOffsetX() {
    return offsetX;
  }


  /**
   * Sets the value of the offsetX property.
   * 
   * @param value
   *        allowed object is {@link BigDecimal }
   */
  public void setOffsetX(BigDecimal value) {
    this.offsetX = value;
  }


  /**
   * Gets the value of the offsetY property.
   * 
   * @return
   *         possible object is {@link BigDecimal }
   */
  public BigDecimal getOffsetY() {
    return offsetY;
  }


  /**
   * Sets the value of the offsetY property.
   * 
   * @param value
   *        allowed object is {@link BigDecimal }
   */
  public void setOffsetY(BigDecimal value) {
    this.offsetY = value;
  }
}
