/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml._2001.ns.celldesigner;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

// TODO: Auto-generated Javadoc
/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.sbml._2001.ns.celldesigner package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  /** The Constant _ReactionType_QNAME. */
  private final static QName _ReactionType_QNAME          = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "reactionType");
  /** The Constant _Hypothetical_QNAME. */
  private final static QName _Hypothetical_QNAME          = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "hypothetical");
  /** The Constant _AntisensernaReference_QNAME. */
  private final static QName _AntisensernaReference_QNAME = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "antisensernaReference");
  /** The Constant _ComplexSpecies_QNAME. */
  private final static QName _ComplexSpecies_QNAME        = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "complexSpecies");
  /** The Constant _Class_QNAME. */
  private final static QName _Class_QNAME                 = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "class");
  /** The Constant _Homodimer_QNAME. */
  private final static QName _Homodimer_QNAME             = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "homodimer");
  /** The Constant _Name_QNAME. */
  private final static QName _Name_QNAME                  = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "name");
  /** The Constant _Alias_QNAME. */
  private final static QName _Alias_QNAME                 = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "alias");
  /** The Constant _Activity_QNAME. */
  private final static QName _Activity_QNAME              = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "activity");
  /** The Constant _ModelVersion_QNAME. */
  private final static QName _ModelVersion_QNAME          = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "modelVersion");
  /** The Constant _ProteinReference_QNAME. */
  private final static QName _ProteinReference_QNAME      = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "proteinReference");
  /** The Constant _RnaReference_QNAME. */
  private final static QName _RnaReference_QNAME          = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "rnaReference");
  /** The Constant _PositionToCompartment_QNAME. */
  private final static QName _PositionToCompartment_QNAME = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "positionToCompartment");
  /** The Constant _GeneReference_QNAME. */
  private final static QName _GeneReference_QNAME         = new QName(
                                                            "http://www.sbml.org/2001/ns/celldesigner",
                                                            "geneReference");


  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package: org.sbml._2001.ns.celldesigner
   */
  public ObjectFactory() {
  }


  /**
   * Create an instance of {@link ListOfRegions }.
   *
   * @return the list of regions
   */
  public ListOfRegions createListOfRegions() {
    return new ListOfRegions();
  }


  /**
   * Create an instance of {@link LayerSpeciesAlias }.
   *
   * @return the layer species alias
   */
  public LayerSpeciesAlias createLayerSpeciesAlias() {
    return new LayerSpeciesAlias();
  }


  /**
   * Create an instance of {@link ListOfModifications }.
   *
   * @return the list of modifications
   */
  public ListOfModifications createListOfModifications() {
    return new ListOfModifications();
  }


  /**
   * Create an instance of {@link Species }.
   *
   * @return the species
   */
  public Species createSpecies() {
    return new Species();
  }


  /**
   * Create an instance of {@link ListOfComplexSpeciesAliases }.
   *
   * @return the list of complex species aliases
   */
  public ListOfComplexSpeciesAliases createListOfComplexSpeciesAliases() {
    return new ListOfComplexSpeciesAliases();
  }


  /**
   * Create an instance of
   * {@link org.sbml._2001.ns.celldesigner.ComplexSpeciesAlias }
   *
   * @return the complex species alias
   */
  public org.sbml._2001.ns.celldesigner.ComplexSpeciesAlias createComplexSpeciesAlias() {
    return new org.sbml._2001.ns.celldesigner.ComplexSpeciesAlias();
  }


  /**
   * Create an instance of {@link ReactionAnnotationType }.
   *
   * @return the reaction annotation type
   */
  public ReactionAnnotationType createReactionAnnotationType() {
    return new ReactionAnnotationType();
  }


  /**
   * Create an instance of {@link ModelAnnotationType }.
   *
   * @return the model annotation type
   */
  public ModelAnnotationType createModelAnnotationType() {
    return new ModelAnnotationType();
  }


  /**
   * Create an instance of {@link SpeciesAnnotationType }.
   *
   * @return the species annotation type
   */
  public SpeciesAnnotationType createSpeciesAnnotationType() {
    return new SpeciesAnnotationType();
  }


  /**
   * Create an instance of {@link CompartmentAnnotationType }.
   *
   * @return the compartment annotation type
   */
  public CompartmentAnnotationType createCompartmentAnnotationType() {
    return new CompartmentAnnotationType();
  }


  /**
   * Create an instance of {@link SpeciesReferenceAnnotationType }.
   *
   * @return the species reference annotation type
   */
  public SpeciesReferenceAnnotationType createSpeciesReferenceAnnotationType() {
    return new SpeciesReferenceAnnotationType();
  }


  /**
   * Create an instance of {@link ModelDisplay }.
   *
   * @return the model display
   */
  public ModelDisplay createModelDisplay() {
    return new ModelDisplay();
  }


  /**
   * Create an instance of {@link DoubleLine }.
   *
   * @return the double line
   */
  public DoubleLine createDoubleLine() {
    return new DoubleLine();
  }


  /**
   * Create an instance of {@link ReactantLink }.
   *
   * @return the reactant link
   */
  public ReactantLink createReactantLink() {
    return new ReactantLink();
  }


  /**
   * Create an instance of {@link ListOfAntisenseRNAs }.
   *
   * @return the list of antisense RN as
   */
  public ListOfAntisenseRNAs createListOfAntisenseRNAs() {
    return new ListOfAntisenseRNAs();
  }


  /**
   * Create an instance of {@link Paint }.
   *
   * @return the paint
   */
  public Paint createPaint() {
    return new Paint();
  }


  /**
   * Create an instance of {@link Halo }.
   *
   * @return the halo
   */
  public Halo createHalo() {
    return new Halo();
  }


  /**
   * Create an instance of {@link ListOfProteins }.
   *
   * @return the list of proteins
   */
  public ListOfProteins createListOfProteins() {
    return new ListOfProteins();
  }


  /**
   * Create an instance of {@link ListOfInternalOperatorsInBlockDiagram }.
   *
   * @return the list of internal operators in block diagram
   */
  public ListOfInternalOperatorsInBlockDiagram createListOfInternalOperatorsInBlockDiagram() {
    return new ListOfInternalOperatorsInBlockDiagram();
  }


  /**
   * Create an instance of {@link InternalOperatorValueInBlockDiagram }.
   *
   * @return the internal operator value in block diagram
   */
  public InternalOperatorValueInBlockDiagram createInternalOperatorValueInBlockDiagram() {
    return new InternalOperatorValueInBlockDiagram();
  }


  /**
   * Create an instance of {@link StructuralStateAngle }.
   *
   * @return the structural state angle
   */
  public StructuralStateAngle createStructuralStateAngle() {
    return new StructuralStateAngle();
  }


  /**
   * Create an instance of {@link KeyInfo }.
   *
   * @return the key info
   */
  public KeyInfo createKeyInfo() {
    return new KeyInfo();
  }


  /**
   * Create an instance of {@link Protein }.
   *
   * @return the protein
   */
  public Protein createProtein() {
    return new Protein();
  }


  /**
   * Create an instance of {@link Block }.
   *
   * @return the block
   */
  public Block createBlock() {
    return new Block();
  }


  /**
   * Create an instance of {@link State }.
   *
   * @return the state
   */
  public State createState() {
    return new State();
  }


  /**
   * Create an instance of {@link ListOfFreeLines }.
   *
   * @return the list of free lines
   */
  public ListOfFreeLines createListOfFreeLines() {
    return new ListOfFreeLines();
  }


  /**
   * Create an instance of {@link ConnectScheme }.
   *
   * @return the connect scheme
   */
  public ConnectScheme createConnectScheme() {
    return new ConnectScheme();
  }


  /**
   * Create an instance of {@link BoxSize }.
   *
   * @return the box size
   */
  public BoxSize createBoxSize() {
    return new BoxSize();
  }


  /**
   * Create an instance of {@link Canvas }.
   *
   * @return the canvas
   */
  public Canvas createCanvas() {
    return new Canvas();
  }


  /**
   * Create an instance of {@link ListOfBlockDiagrams }.
   *
   * @return the list of block diagrams
   */
  public ListOfBlockDiagrams createListOfBlockDiagrams() {
    return new ListOfBlockDiagrams();
  }


  /**
   * Create an instance of {@link LayerLineBounds }.
   *
   * @return the layer line bounds
   */
  public LayerLineBounds createLayerLineBounds() {
    return new LayerLineBounds();
  }


  /**
   * Create an instance of {@link Gene }.
   *
   * @return the gene
   */
  public Gene createGene() {
    return new Gene();
  }


  /**
   * Create an instance of {@link SingleLine }.
   *
   * @return the single line
   */
  public SingleLine createSingleLine() {
    return new SingleLine();
  }


  /**
   * Create an instance of {@link EffectTargetInBlockDiagram }.
   *
   * @return the effect target in block diagram
   */
  public EffectTargetInBlockDiagram createEffectTargetInBlockDiagram() {
    return new EffectTargetInBlockDiagram();
  }


  /**
   * Create an instance of {@link InternalOperatorInBlockDiagram }.
   *
   * @return the internal operator in block diagram
   */
  public InternalOperatorInBlockDiagram createInternalOperatorInBlockDiagram() {
    return new InternalOperatorInBlockDiagram();
  }


  /**
   * Create an instance of {@link BaseReactant }.
   *
   * @return the base reactant
   */
  public BaseReactant createBaseReactant() {
    return new BaseReactant();
  }


  /**
   * Create an instance of {@link ListOfIncludedSpecies }.
   *
   * @return the list of included species
   */
  public ListOfIncludedSpecies createListOfIncludedSpecies() {
    return new ListOfIncludedSpecies();
  }


  /**
   * Create an instance of {@link EndPointInBlockDiagram }.
   *
   * @return the end point in block diagram
   */
  public EndPointInBlockDiagram createEndPointInBlockDiagram() {
    return new EndPointInBlockDiagram();
  }


  /**
   * Create an instance of {@link ListOfSquares }.
   *
   * @return the list of squares
   */
  public ListOfSquares createListOfSquares() {
    return new ListOfSquares();
  }


  /**
   * Create an instance of {@link BaseReactants }.
   *
   * @return the base reactants
   */
  public BaseReactants createBaseReactants() {
    return new BaseReactants();
  }


  /**
   * Create an instance of {@link Bounds }.
   *
   * @return the bounds
   */
  public Bounds createBounds() {
    return new Bounds();
  }


  /**
   * Create an instance of {@link BriefView }.
   *
   * @return the brief view
   */
  public BriefView createBriefView() {
    return new BriefView();
  }


  /**
   * Create an instance of {@link ListOfRNAs }.
   *
   * @return the list of RN as
   */
  public ListOfRNAs createListOfRNAs() {
    return new ListOfRNAs();
  }


  /**
   * Create an instance of {@link LayerCompartmentAlias }.
   *
   * @return the layer compartment alias
   */
  public LayerCompartmentAlias createLayerCompartmentAlias() {
    return new LayerCompartmentAlias();
  }


  /**
   * Create an instance of {@link StructuralStates }.
   *
   * @return the structural states
   */
  public StructuralStates createStructuralStates() {
    return new StructuralStates();
  }


  /**
   * Create an instance of {@link DegradedShapeInBlockDiagram }.
   *
   * @return the degraded shape in block diagram
   */
  public DegradedShapeInBlockDiagram createDegradedShapeInBlockDiagram() {
    return new DegradedShapeInBlockDiagram();
  }


  /**
   * Create an instance of {@link CompartmentAlias }.
   *
   * @return the compartment alias
   */
  public CompartmentAlias createCompartmentAlias() {
    return new CompartmentAlias();
  }


  /**
   * Create an instance of {@link BlockDiagram }.
   *
   * @return the block diagram
   */
  public BlockDiagram createBlockDiagram() {
    return new BlockDiagram();
  }


  /**
   * Create an instance of {@link ListOfCatalyzedReactions }.
   *
   * @return the list of catalyzed reactions
   */
  public ListOfCatalyzedReactions createListOfCatalyzedReactions() {
    return new ListOfCatalyzedReactions();
  }


  /**
   * Create an instance of {@link Catalyzed }.
   *
   * @return the catalyzed
   */
  public Catalyzed createCatalyzed() {
    return new Catalyzed();
  }


  /**
   * Create an instance of {@link Layer }.
   *
   * @return the layer
   */
  public Layer createLayer() {
    return new Layer();
  }


  /**
   * Create an instance of {@link ListOfSpeciesAliases }.
   *
   * @return the list of species aliases
   */
  public ListOfSpeciesAliases createListOfSpeciesAliases() {
    return new ListOfSpeciesAliases();
  }


  /**
   * Create an instance of {@link SpeciesTag }.
   *
   * @return the species tag
   */
  public SpeciesTag createSpeciesTag() {
    return new SpeciesTag();
  }


  /**
   * Create an instance of {@link ListOfStructuralStates }.
   *
   * @return the list of structural states
   */
  public ListOfStructuralStates createListOfStructuralStates() {
    return new ListOfStructuralStates();
  }


  /**
   * Create an instance of {@link SpeciesIdentity }.
   *
   * @return the species identity
   */
  public SpeciesIdentity createSpeciesIdentity() {
    return new SpeciesIdentity();
  }


  /**
   * Create an instance of {@link BaseProduct }.
   *
   * @return the base product
   */
  public BaseProduct createBaseProduct() {
    return new BaseProduct();
  }


  /**
   * Create an instance of {@link ListOfExternalNamesForResidue }.
   *
   * @return the list of external names for residue
   */
  public ListOfExternalNamesForResidue createListOfExternalNamesForResidue() {
    return new ListOfExternalNamesForResidue();
  }


  /**
   * Create an instance of {@link ModificationResidue }.
   *
   * @return the modification residue
   */
  public ModificationResidue createModificationResidue() {
    return new ModificationResidue();
  }


  /**
   * Create an instance of {@link EffectSiteInBlockDiagram }.
   *
   * @return the effect site in block diagram
   */
  public EffectSiteInBlockDiagram createEffectSiteInBlockDiagram() {
    return new EffectSiteInBlockDiagram();
  }


  /**
   * Create an instance of {@link ListOfInternalLinksInBlockDiagram }.
   *
   * @return the list of internal links in block diagram
   */
  public ListOfInternalLinksInBlockDiagram createListOfInternalLinksInBlockDiagram() {
    return new ListOfInternalLinksInBlockDiagram();
  }


  /**
   * Create an instance of {@link AntisenseRNA }.
   *
   * @return the antisense RNA
   */
  public AntisenseRNA createAntisenseRNA() {
    return new AntisenseRNA();
  }


  /**
   * Create an instance of {@link ExternalConnectionInBlockDiagram }.
   *
   * @return the external connection in block diagram
   */
  public ExternalConnectionInBlockDiagram createExternalConnectionInBlockDiagram() {
    return new ExternalConnectionInBlockDiagram();
  }


  /**
   * Create an instance of {@link ListOfGenes }.
   *
   * @return the list of genes
   */
  public ListOfGenes createListOfGenes() {
    return new ListOfGenes();
  }


  /**
   * Create an instance of {@link LinkAnchor }.
   *
   * @return the link anchor
   */
  public LinkAnchor createLinkAnchor() {
    return new LinkAnchor();
  }


  /**
   * Create an instance of {@link UsualView }.
   *
   * @return the usual view
   */
  public UsualView createUsualView() {
    return new UsualView();
  }


  /**
   * Create an instance of {@link ListOfLayers }.
   *
   * @return the list of layers
   */
  public ListOfLayers createListOfLayers() {
    return new ListOfLayers();
  }


  /**
   * Create an instance of {@link Notes }.
   *
   * @return the notes
   */
  public Notes createNotes() {
    return new Notes();
  }


  /**
   * Create an instance of {@link RNA }.
   *
   * @return the rna
   */
  public RNA createRNA() {
    return new RNA();
  }


  /**
   * Create an instance of {@link DegradedInBlockDiagram }.
   *
   * @return the degraded in block diagram
   */
  public DegradedInBlockDiagram createDegradedInBlockDiagram() {
    return new DegradedInBlockDiagram();
  }


  /**
   * Create an instance of {@link ExternalNameForResidue }.
   *
   * @return the external name for residue
   */
  public ExternalNameForResidue createExternalNameForResidue() {
    return new ExternalNameForResidue();
  }


  /**
   * Create an instance of {@link View }.
   *
   * @return the view
   */
  public View createView() {
    return new View();
  }


  /**
   * Create an instance of {@link ListOfLineDirection }.
   *
   * @return the list of line direction
   */
  public ListOfLineDirection createListOfLineDirection() {
    return new ListOfLineDirection();
  }


  /**
   * Create an instance of {@link TagBounds }.
   *
   * @return the tag bounds
   */
  public TagBounds createTagBounds() {
    return new TagBounds();
  }


  /**
   * Create an instance of {@link TagEdgeLine }.
   *
   * @return the tag edge line
   */
  public TagEdgeLine createTagEdgeLine() {
    return new TagEdgeLine();
  }


  /**
   * Create an instance of {@link ListOfBindingSitesInBlockDiagram }.
   *
   * @return the list of binding sites in block diagram
   */
  public ListOfBindingSitesInBlockDiagram createListOfBindingSitesInBlockDiagram() {
    return new ListOfBindingSitesInBlockDiagram();
  }


  /**
   * Create an instance of {@link ProductLink }.
   *
   * @return the product link
   */
  public ProductLink createProductLink() {
    return new ProductLink();
  }


  /**
   * Create an instance of {@link ListOfTexts }.
   *
   * @return the list of texts
   */
  public ListOfTexts createListOfTexts() {
    return new ListOfTexts();
  }


  /**
   * Create an instance of {@link InternalLinkInBlockDiagram }.
   *
   * @return the internal link in block diagram
   */
  public InternalLinkInBlockDiagram createInternalLinkInBlockDiagram() {
    return new InternalLinkInBlockDiagram();
  }


  /**
   * Create an instance of {@link ListOfModification }.
   *
   * @return the list of modification
   */
  public ListOfModification createListOfModification() {
    return new ListOfModification();
  }


  /**
   * Create an instance of {@link Group }.
   *
   * @return the group
   */
  public Group createGroup() {
    return new Group();
  }


  /**
   * Create an instance of {@link LineDirection }.
   *
   * @return the line direction
   */
  public LineDirection createLineDirection() {
    return new LineDirection();
  }


  /**
   * Create an instance of {@link ListOfReactantLinks }.
   *
   * @return the list of reactant links
   */
  public ListOfReactantLinks createListOfReactantLinks() {
    return new ListOfReactantLinks();
  }


  /**
   * Create an instance of {@link Info }.
   *
   * @return the info
   */
  public Info createInfo() {
    return new Info();
  }


  /**
   * Create an instance of {@link Offset }.
   *
   * @return the offset
   */
  public Offset createOffset() {
    return new Offset();
  }


  /**
   * Create an instance of {@link InnerPosition }.
   *
   * @return the inner position
   */
  public InnerPosition createInnerPosition() {
    return new InnerPosition();
  }


  /**
   * Create an instance of {@link org.sbml._2001.ns.celldesigner.Modification }
   *
   * @return the modification
   */
  public org.sbml._2001.ns.celldesigner.Modification createModification() {
    return new org.sbml._2001.ns.celldesigner.Modification();
  }


  /**
   * Create an instance of {@link ListOfEffectSitesInBlockDiagram }.
   *
   * @return the list of effect sites in block diagram
   */
  public ListOfEffectSitesInBlockDiagram createListOfEffectSitesInBlockDiagram() {
    return new ListOfEffectSitesInBlockDiagram();
  }


  /**
   * Create an instance of {@link LayerFreeLine }.
   *
   * @return the layer free line
   */
  public LayerFreeLine createLayerFreeLine() {
    return new LayerFreeLine();
  }


  /**
   * Create an instance of {@link ListOfSpeciesTag }.
   *
   * @return the list of species tag
   */
  public ListOfSpeciesTag createListOfSpeciesTag() {
    return new ListOfSpeciesTag();
  }


  /**
   * Create an instance of {@link EditPoints }.
   *
   * @return the edits the points
   */
  public EditPoints createEditPoints() {
    return new EditPoints();
  }


  /**
   * Create an instance of {@link org.sbml._2001.ns.celldesigner.Region }
   *
   * @return the region
   */
  public org.sbml._2001.ns.celldesigner.Region createRegion() {
    return new org.sbml._2001.ns.celldesigner.Region();
  }


  /**
   * Create an instance of {@link ListOfProductLinks }.
   *
   * @return the list of product links
   */
  public ListOfProductLinks createListOfProductLinks() {
    return new ListOfProductLinks();
  }


  /**
   * Create an instance of {@link ResidueInBlockDiagram }.
   *
   * @return the residue in block diagram
   */
  public ResidueInBlockDiagram createResidueInBlockDiagram() {
    return new ResidueInBlockDiagram();
  }


  /**
   * Create an instance of {@link BindingRegion }.
   *
   * @return the binding region
   */
  public BindingRegion createBindingRegion() {
    return new BindingRegion();
  }


  /**
   * Create an instance of {@link Line }.
   *
   * @return the line
   */
  public Line createLine() {
    return new Line();
  }


  /**
   * Create an instance of {@link ListOfCompartmentAliases }.
   *
   * @return the list of compartment aliases
   */
  public ListOfCompartmentAliases createListOfCompartmentAliases() {
    return new ListOfCompartmentAliases();
  }


  /**
   * Create an instance of {@link LinkTarget }.
   *
   * @return the link target
   */
  public LinkTarget createLinkTarget() {
    return new LinkTarget();
  }


  /**
   * Create an instance of {@link Point }.
   *
   * @return the point
   */
  public Point createPoint() {
    return new Point();
  }


  /**
   * Create an instance of {@link ListOfGroups }.
   *
   * @return the list of groups
   */
  public ListOfGroups createListOfGroups() {
    return new ListOfGroups();
  }


  /**
   * Create an instance of {@link ListOfResiduesInBlockDiagram }.
   *
   * @return the list of residues in block diagram
   */
  public ListOfResiduesInBlockDiagram createListOfResiduesInBlockDiagram() {
    return new ListOfResiduesInBlockDiagram();
  }


  /**
   * Create an instance of {@link BindingSiteInBlockDiagram }.
   *
   * @return the binding site in block diagram
   */
  public BindingSiteInBlockDiagram createBindingSiteInBlockDiagram() {
    return new BindingSiteInBlockDiagram();
  }


  /**
   * Create an instance of {@link ListOfBindingRegions }.
   *
   * @return the list of binding regions
   */
  public ListOfBindingRegions createListOfBindingRegions() {
    return new ListOfBindingRegions();
  }


  /**
   * Create an instance of {@link ListOfModificationResidues }.
   *
   * @return the list of modification residues
   */
  public ListOfModificationResidues createListOfModificationResidues() {
    return new ListOfModificationResidues();
  }


  /**
   * Create an instance of {@link EffectInBlockDiagram }.
   *
   * @return the effect in block diagram
   */
  public EffectInBlockDiagram createEffectInBlockDiagram() {
    return new EffectInBlockDiagram();
  }


  /**
   * Create an instance of {@link SpeciesAlias }.
   *
   * @return the species alias
   */
  public SpeciesAlias createSpeciesAlias() {
    return new SpeciesAlias();
  }


  /**
   * Create an instance of {@link StartingPointInBlockDiagram }.
   *
   * @return the starting point in block diagram
   */
  public StartingPointInBlockDiagram createStartingPointInBlockDiagram() {
    return new StartingPointInBlockDiagram();
  }


  /**
   * Create an instance of {@link BaseProducts }.
   *
   * @return the base products
   */
  public BaseProducts createBaseProducts() {
    return new BaseProducts();
  }


  /**
   * Create an instance of {@link ListOfExternalConnectionsInBlockDiagram }.
   *
   * @return the list of external connections in block diagram
   */
  public ListOfExternalConnectionsInBlockDiagram createListOfExternalConnectionsInBlockDiagram() {
    return new ListOfExternalConnectionsInBlockDiagram();
  }


  /**
   * Create an instance of {@link LineType2 }.
   *
   * @return the line type 2
   */
  public LineType2 createLineType2() {
    return new LineType2();
  }


  /**
   * Create an instance of {@link ListOfRegions.Region }
   *
   * @return the region
   */
  public ListOfRegions.Region createListOfRegionsRegion() {
    return new ListOfRegions.Region();
  }


  /**
   * Create an instance of {@link LayerSpeciesAlias.Font }
   *
   * @return the font
   */
  public LayerSpeciesAlias.Font createLayerSpeciesAliasFont() {
    return new LayerSpeciesAlias.Font();
  }


  /**
   * Create an instance of {@link ListOfModifications.Modification }
   *
   * @return the modification
   */
  public ListOfModifications.Modification createListOfModificationsModification() {
    return new ListOfModifications.Modification();
  }


  /**
   * Create an instance of {@link Species.Annotation }
   *
   * @return the annotation
   */
  public Species.Annotation createSpeciesAnnotation() {
    return new Species.Annotation();
  }


  /**
   * Create an instance of
   * {@link ListOfComplexSpeciesAliases.ComplexSpeciesAlias }
   *
   * @return the complex species alias
   */
  public ListOfComplexSpeciesAliases.ComplexSpeciesAlias createListOfComplexSpeciesAliasesComplexSpeciesAlias() {
    return new ListOfComplexSpeciesAliases.ComplexSpeciesAlias();
  }


  /**
   * Create an instance of
   * {@link org.sbml._2001.ns.celldesigner.ComplexSpeciesAlias.BackupSize }
   *
   * @return the backup size
   */
  public org.sbml._2001.ns.celldesigner.ComplexSpeciesAlias.BackupSize createComplexSpeciesAliasBackupSize() {
    return new org.sbml._2001.ns.celldesigner.ComplexSpeciesAlias.BackupSize();
  }


  /**
   * Create an instance of {@link ReactionAnnotationType.Extension }
   *
   * @return the extension
   */
  public ReactionAnnotationType.Extension createReactionAnnotationTypeExtension() {
    return new ReactionAnnotationType.Extension();
  }


  /**
   * Create an instance of {@link ModelAnnotationType.Extension }
   *
   * @return the extension
   */
  public ModelAnnotationType.Extension createModelAnnotationTypeExtension() {
    return new ModelAnnotationType.Extension();
  }


  /**
   * Create an instance of {@link SpeciesAnnotationType.Extension }
   *
   * @return the extension
   */
  public SpeciesAnnotationType.Extension createSpeciesAnnotationTypeExtension() {
    return new SpeciesAnnotationType.Extension();
  }


  /**
   * Create an instance of {@link CompartmentAnnotationType.Extension }
   *
   * @return the extension
   */
  public CompartmentAnnotationType.Extension createCompartmentAnnotationTypeExtension() {
    return new CompartmentAnnotationType.Extension();
  }


  /**
   * Create an instance of {@link SpeciesReferenceAnnotationType.Extension }
   *
   * @return the extension
   */
  public SpeciesReferenceAnnotationType.Extension createSpeciesReferenceAnnotationTypeExtension() {
    return new SpeciesReferenceAnnotationType.Extension();
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "reactionType")
  public JAXBElement<String> createReactionType(String value) {
    return new JAXBElement<String>(_ReactionType_QNAME, String.class, null,
      value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
   * .
   *
   * @param value
   *        the value
   * @return the JAXB element< boolean>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "hypothetical")
  public JAXBElement<Boolean> createHypothetical(Boolean value) {
    return new JAXBElement<Boolean>(_Hypothetical_QNAME, Boolean.class, null,
      value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "antisensernaReference")
  public JAXBElement<String> createAntisensernaReference(String value) {
    return new JAXBElement<String>(_AntisensernaReference_QNAME, String.class,
      null, value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "complexSpecies")
  public JAXBElement<String> createComplexSpecies(String value) {
    return new JAXBElement<String>(_ComplexSpecies_QNAME, String.class, null,
      value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "class")
  public JAXBElement<String> createClass(String value) {
    return new JAXBElement<String>(_Class_QNAME, String.class, null, value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
   * {@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< big integer>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "homodimer")
  public JAXBElement<BigInteger> createHomodimer(BigInteger value) {
    return new JAXBElement<BigInteger>(_Homodimer_QNAME, BigInteger.class,
      null, value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "name")
  public JAXBElement<String> createName(String value) {
    return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "alias")
  public JAXBElement<String> createAlias(String value) {
    return new JAXBElement<String>(_Alias_QNAME, String.class, null, value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "activity")
  public JAXBElement<String> createActivity(String value) {
    return new JAXBElement<String>(_Activity_QNAME, String.class, null, value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
   * {@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< big decimal>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "modelVersion")
  public JAXBElement<BigDecimal> createModelVersion(BigDecimal value) {
    return new JAXBElement<BigDecimal>(_ModelVersion_QNAME, BigDecimal.class,
      null, value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "proteinReference")
  public JAXBElement<String> createProteinReference(String value) {
    return new JAXBElement<String>(_ProteinReference_QNAME, String.class, null,
      value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "rnaReference")
  public JAXBElement<String> createRnaReference(String value) {
    return new JAXBElement<String>(_RnaReference_QNAME, String.class, null,
      value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "positionToCompartment")
  public JAXBElement<String> createPositionToCompartment(String value) {
    return new JAXBElement<String>(_PositionToCompartment_QNAME, String.class,
      null, value);
  }


  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >} .
   *
   * @param value
   *        the value
   * @return the JAXB element< string>
   */
  @XmlElementDecl(namespace = "http://www.sbml.org/2001/ns/celldesigner", name = "geneReference")
  public JAXBElement<String> createGeneReference(String value) {
    return new JAXBElement<String>(_GeneReference_QNAME, String.class, null,
      value);
  }
}
