//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.sbml._2001.ns.celldesigner;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * Annotation for species.
 * 
 * <p>Java class for speciesAnnotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="speciesAnnotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extension">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element ref="{http://www.sbml.org/2001/ns/celldesigner}positionToCompartment"/>
 *                     &lt;element ref="{http://www.sbml.org/2001/ns/celldesigner}complexSpecies"/>
 *                   &lt;/choice>
 *                   &lt;element name="speciesIdentity" type="{http://www.sbml.org/2001/ns/celldesigner}speciesIdentity"/>
 *                   &lt;element name="listOfCatalyzedReactions" type="{http://www.sbml.org/2001/ns/celldesigner}listOfCatalyzedReactions" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "speciesAnnotationType", propOrder = {
    "extension",
    "any"
})
public class SpeciesAnnotationType {

    @XmlElement(required = true)
    protected SpeciesAnnotationType.Extension extension;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link SpeciesAnnotationType.Extension }
     *     
     */
    public SpeciesAnnotationType.Extension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeciesAnnotationType.Extension }
     *     
     */
    public void setExtension(SpeciesAnnotationType.Extension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element ref="{http://www.sbml.org/2001/ns/celldesigner}positionToCompartment"/>
     *           &lt;element ref="{http://www.sbml.org/2001/ns/celldesigner}complexSpecies"/>
     *         &lt;/choice>
     *         &lt;element name="speciesIdentity" type="{http://www.sbml.org/2001/ns/celldesigner}speciesIdentity"/>
     *         &lt;element name="listOfCatalyzedReactions" type="{http://www.sbml.org/2001/ns/celldesigner}listOfCatalyzedReactions" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "positionToCompartment",
        "complexSpecies",
        "speciesIdentity",
        "listOfCatalyzedReactions"
    })
    public static class Extension {

        protected String positionToCompartment;
        protected String complexSpecies;
        @XmlElement(required = true)
        protected SpeciesIdentity speciesIdentity;
        protected ListOfCatalyzedReactions listOfCatalyzedReactions;

        /**
         * Gets the value of the positionToCompartment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPositionToCompartment() {
            return positionToCompartment;
        }

        /**
         * Sets the value of the positionToCompartment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPositionToCompartment(String value) {
            this.positionToCompartment = value;
        }

        /**
         * Gets the value of the complexSpecies property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComplexSpecies() {
            return complexSpecies;
        }

        /**
         * Sets the value of the complexSpecies property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComplexSpecies(String value) {
            this.complexSpecies = value;
        }

        /**
         * Gets the value of the speciesIdentity property.
         * 
         * @return
         *     possible object is
         *     {@link SpeciesIdentity }
         *     
         */
        public SpeciesIdentity getSpeciesIdentity() {
            return speciesIdentity;
        }

        /**
         * Sets the value of the speciesIdentity property.
         * 
         * @param value
         *     allowed object is
         *     {@link SpeciesIdentity }
         *     
         */
        public void setSpeciesIdentity(SpeciesIdentity value) {
            this.speciesIdentity = value;
        }

        /**
         * Gets the value of the listOfCatalyzedReactions property.
         * 
         * @return
         *     possible object is
         *     {@link ListOfCatalyzedReactions }
         *     
         */
        public ListOfCatalyzedReactions getListOfCatalyzedReactions() {
            return listOfCatalyzedReactions;
        }

        /**
         * Sets the value of the listOfCatalyzedReactions property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListOfCatalyzedReactions }
         *     
         */
        public void setListOfCatalyzedReactions(ListOfCatalyzedReactions value) {
            this.listOfCatalyzedReactions = value;
        }

    }

}
