/*******************************************************************************
 * Copyright 2016 Kaito Ii, Akira Funahashi
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.05.30 at 07:47:34 PM JST
//
package org.sbml._2001.ns.celldesigner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for TagBounds complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TagBounds">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="w" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="h" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TagBounds")
public class TagBounds {

  /** The x. */
  @XmlAttribute(name = "x")
  protected Double x;
  /** The y. */
  @XmlAttribute(name = "y")
  protected Double y;
  /** The w. */
  @XmlAttribute(name = "w")
  protected Double w;
  /** The h. */
  @XmlAttribute(name = "h")
  protected Double h;


  /**
   * Gets the value of the x property.
   * 
   * @return
   *         possible object is {@link Double }
   */
  public Double getX() {
    return x;
  }


  /**
   * Sets the value of the x property.
   * 
   * @param value
   *        allowed object is {@link Double }
   */
  public void setX(Double value) {
    this.x = value;
  }


  /**
   * Gets the value of the y property.
   * 
   * @return
   *         possible object is {@link Double }
   */
  public Double getY() {
    return y;
  }


  /**
   * Sets the value of the y property.
   * 
   * @param value
   *        allowed object is {@link Double }
   */
  public void setY(Double value) {
    this.y = value;
  }


  /**
   * Gets the value of the w property.
   * 
   * @return
   *         possible object is {@link Double }
   */
  public Double getW() {
    return w;
  }


  /**
   * Sets the value of the w property.
   * 
   * @param value
   *        allowed object is {@link Double }
   */
  public void setW(Double value) {
    this.w = value;
  }


  /**
   * Gets the value of the h property.
   * 
   * @return
   *         possible object is {@link Double }
   */
  public Double getH() {
    return h;
  }


  /**
   * Sets the value of the h property.
   * 
   * @param value
   *        allowed object is {@link Double }
   */
  public void setH(Double value) {
    this.h = value;
  }
}
